### ISSUE TITLE
RuntimeError: CUDA error: initialization error

### ISSUE THREAD

**Issue by holalula** [TsinghuaAI/CPM-Finetune#23]
总是会报这个错误，我从git重新装了几次apex也还是有这个问题。奇怪的一点就是无论数据集大小，总是在第3个batch的时候报错。环境是RTX2080*8，NVIDIA-SMI 440.64 ，Driver Version: 440.64，CUDA Version: 10.2，torch1.6.0
************************************************
using world size: 8 and model-parallel size: 8 
 > using dynamic loss scaling
> initializing model parallel with size 8
[2021-03-27 10:39:01,615] [INFO] [checkpointing.py:763:_configure_using_config_file] {'partition_activations': True, 'contiguous_memory_optimization': False, 'cpu_checkpointing': False, 'number_checkpoints': None, 'synchronize_checkpoint_boundary': False, 'profile': False}
[2021-03-27 10:39:01,616] [INFO] [checkpointing.py:251:model_parallel_cuda_manual_seed] > initializing model parallel cuda seeds on global rank 0, model parallel rank 0, and data parallel rank 0 with model parallel seed: 26051 and data parallel seed: 23333
Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Building prefix dict from the default dictionary ...
Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Loading model from cache /tmp/jieba.cache
Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
  0%|                                                                                                                                                             | 0/23532 [00:00<?, ?it/s]Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Loading model cost 0.749 seconds.
Prefix dict has been built successfully.
Loading model cost 0.754 seconds.
Prefix dict has been built successfully.
Loading model cost 0.775 seconds.
Prefix dict has been built successfully.
Loading model cost 0.734 seconds.
Prefix dict has been built successfully.
  0%|                                                                                                                                                   | 1/23532 [00:00<4:48:24,  1.36it/s]Loading model cost 0.761 seconds.
Prefix dict has been built successfully.
Loading model cost 0.762 seconds.
Prefix dict has been built successfully.
Loading model cost 0.777 seconds.
Prefix dict has been built successfully.
Loading model cost 0.788 seconds.
Prefix dict has been built successfully.
100%|???????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????| 23532/23532 [00:08<00:00, 2781.77it/s]
100%|???????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????| 23532/23532 [00:07<00:00, 3110.19it/s]
building GPT2 model ...
 > number of parameters on model parallel rank 1: 327362560
 > number of parameters on model parallel rank 4: 327362560
 > number of parameters on model parallel rank 2: 327362560
 > number of parameters on model parallel rank 0: 327362560
 > number of parameters on model parallel rank 5: 327362560
 > number of parameters on model parallel rank 7: 327362560
 > number of parameters on model parallel rank 6: 327362560
 > number of parameters on model parallel rank 3: 327362560
130 258
Optimizer = FusedAdam
130 258
[2021-03-27 10:39:59,701] [INFO] [engine.py:591:_configure_optimizer] Removing param_group that has no 'params'in the client Optimizer
Optimizer = FusedAdam
[2021-03-27 10:39:59,879] [INFO] [engine.py:591:_configure_optimizer] Removing param_group that has no 'params'in the client Optimizer
130 258
Optimizer = FusedAdam
[2021-03-27 10:40:00,245] [INFO] [engine.py:591:_configure_optimizer] Removing param_group that has no 'params'in the client Optimizer
130 258
Using /home/ztx/.cache/torch_extensions as PyTorch extensions root...
Optimizer = FusedAdam
learning rate decaying linear
DeepSpeed is enabled.
[2021-03-27 10:40:00,464] [INFO] [logging.py:60:log_dist] [Rank 0] DeepSpeed info: version=0.3.13, git-hash=unknown, git-branch=unknown
[2021-03-27 10:40:00,476] [INFO] [engine.py:591:_configure_optimizer] Removing param_group that has no 'params'in the client Optimizer
[2021-03-27 10:40:00,476] [INFO] [engine.py:596:_configure_optimizer] Using client Optimizer as basic optimizer
[2021-03-27 10:40:00,476] [INFO] [engine.py:605:_configure_optimizer] DeepSpeed Basic Optimizer = FusedAdam
[2021-03-27 10:40:00,477] [INFO] [logging.py:60:log_dist] [Rank 0] DeepSpeed Final Optimizer = FusedAdam
[2021-03-27 10:40:00,477] [INFO] [engine.py:443:_configure_lr_scheduler] DeepSpeed using client LR scheduler
[2021-03-27 10:40:00,477] [INFO] [logging.py:60:log_dist] [Rank 0] DeepSpeed LR Scheduler = <learning_rates.AnnealingLR object at 0x7f47a3f915e0>
[2021-03-27 10:40:00,477] [INFO] [logging.py:60:log_dist] [Rank 0] step=0, skipped=0, lr=[0.0, 0.0], mom=[(0.9, 0.999), (0.9, 0.999)]
[2021-03-27 10:40:00,477] [INFO] [config.py:737:print] DeepSpeedEngine configuration:
[2021-03-27 10:40:00,477] [INFO] [config.py:741:print]   activation_checkpointing_config  {
    "contiguous_memory_optimization": false,
    "cpu_checkpointing": false,
    "number_checkpoints": null,
    "partition_activations": true,
    "profile": false,
    "synchronize_checkpoint_boundary": false
}
[2021-03-27 10:40:00,477] [INFO] [config.py:741:print]   allreduce_always_fp32 ........ False
[2021-03-27 10:40:00,477] [INFO] [config.py:741:print]   amp_enabled .................. False
[2021-03-27 10:40:00,477] [INFO] [config.py:741:print]   amp_params ................... False
[2021-03-27 10:40:00,477] [INFO] [config.py:741:print]   checkpoint_tag_validation_enabled  True
[2021-03-27 10:40:00,477] [INFO] [config.py:741:print]   checkpoint_tag_validation_fail  False
[2021-03-27 10:40:00,477] [INFO] [config.py:741:print]   disable_allgather ............ False
[2021-03-27 10:40:00,477] [INFO] [config.py:741:print]   dump_state ................... False
[2021-03-27 10:40:00,477] [INFO] [config.py:741:print]   dynamic_loss_scale_args ...... None
[2021-03-27 10:40:00,478] [INFO] [config.py:741:print]   elasticity_enabled ........... False
[2021-03-27 10:40:00,478] [INFO] [config.py:741:print]   flops_profiler_config ........ {
    "detailed": true,
    "enabled": false,
    "module_depth": -1,
    "profile_step": 1,
    "top_modules": 3
}
[2021-03-27 10:40:00,478] [INFO] [config.py:741:print]   fp16_enabled ................. False
[2021-03-27 10:40:00,478] [INFO] [config.py:741:print]   global_rank .................. 0
[2021-03-27 10:40:00,478] [INFO] [config.py:741:print]   gradient_accumulation_steps .. 4
[2021-03-27 10:40:00,478] [INFO] [config.py:741:print]   gradient_clipping ............ 1.0
[2021-03-27 10:40:00,478] [INFO] [config.py:741:print]   gradient_predivide_factor .... 1.0
[2021-03-27 10:40:00,478] [INFO] [config.py:741:print]   initial_dynamic_scale ........ 4294967296
[2021-03-27 10:40:00,478] [INFO] [config.py:741:print]   loss_scale ................... 0
[2021-03-27 10:40:00,478] [INFO] [config.py:741:print]   memory_breakdown ............. False
[2021-03-27 10:40:00,478] [INFO] [config.py:741:print]   optimizer_legacy_fusion ...... False
[2021-03-27 10:40:00,478] [INFO] [config.py:741:print]   optimizer_name ............... None
[2021-03-27 10:40:00,478] [INFO] [config.py:741:print]   optimizer_params ............. None
[2021-03-27 10:40:00,478] [INFO] [config.py:741:print]   pipeline ..................... {'stages': 'auto', 'partition': 'best', 'seed_layers': False, 'activation_checkpoint_interval': 0}
[2021-03-27 10:40:00,478] [INFO] [config.py:741:print]   pld_enabled .................. False
[2021-03-27 10:40:00,478] [INFO] [config.py:741:print]   pld_params ................... False
[2021-03-27 10:40:00,478] [INFO] [config.py:741:print]   prescale_gradients ........... False
[2021-03-27 10:40:00,478] [INFO] [config.py:741:print]   scheduler_name ............... None
[2021-03-27 10:40:00,478] [INFO] [config.py:741:print]   scheduler_params ............. None
[2021-03-27 10:40:00,478] [INFO] [config.py:741:print]   sparse_attention ............. None
[2021-03-27 10:40:00,478] [INFO] [config.py:741:print]   sparse_gradients_enabled ..... False
[2021-03-27 10:40:00,478] [INFO] [config.py:741:print]   steps_per_print .............. 100000000
[2021-03-27 10:40:00,478] [INFO] [config.py:741:print]   tensorboard_enabled .......... False
[2021-03-27 10:40:00,478] [INFO] [config.py:741:print]   tensorboard_job_name ......... DeepSpeedJobName
[2021-03-27 10:40:00,478] [INFO] [config.py:741:print]   tensorboard_output_path ...... 
[2021-03-27 10:40:00,478] [INFO] [config.py:741:print]   train_batch_size ............. 64
[2021-03-27 10:40:00,478] [INFO] [config.py:741:print]   train_micro_batch_size_per_gpu  16
[2021-03-27 10:40:00,478] [INFO] [config.py:741:print]   wall_clock_breakdown ......... False
[2021-03-27 10:40:00,478] [INFO] [config.py:741:print]   world_size ................... 1
[2021-03-27 10:40:00,478] [INFO] [config.py:741:print]   zero_allow_untested_optimizer  False
[2021-03-27 10:40:00,479] [INFO] [config.py:741:print]   zero_config .................. {
    "allgather_bucket_size": 500000000,
    "allgather_partitions": true,
    "contiguous_gradients": false,
    "cpu_offload": false,
    "cpu_offload_params": false,
    "cpu_offload_use_pin_memory": "cpu_offload_use_pin_memory",
    "elastic_checkpoint": true,
    "load_from_fp32_weights": true,
    "max_live_parameters": 1000000000,
    "max_reuse_distance": 1000000000,
    "overlap_comm": false,
    "param_persistence_threshold": 100000,
    "prefetch_bucket_size": 50000000,
    "reduce_bucket_size": 500000000,
    "reduce_scatter": true,
    "stage": 0,
    "sub_group_size": 1000000000000
}
[2021-03-27 10:40:00,479] [INFO] [config.py:741:print]   zero_enabled ................. False
[2021-03-27 10:40:00,479] [INFO] [config.py:741:print]   zero_optimization_stage ...... 0
[2021-03-27 10:40:00,479] [INFO] [config.py:743:print]   json = {
    "activation_checkpointing":{
        "contiguous_memory_optimization":false,
        "partition_activations":true
    },
    "gradient_accumulation_steps":4,
    "gradient_clipping":1.0,
    "steps_per_print":100000000,
    "train_micro_batch_size_per_gpu":16,
    "wall_clock_breakdown":false
}
Using /home/ztx/.cache/torch_extensions as PyTorch extensions root...
Emitting ninja build file /home/ztx/.cache/torch_extensions/utils/build.ninja...
Building extension module utils...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
Using /home/ztx/.cache/torch_extensions as PyTorch extensions root...
ninja: no work to do.
Loading extension module utils...
Time to load utils op: 0.6361424922943115 seconds
[2021-03-27 10:40:01,006] [INFO] [engine.py:1435:_load_checkpoint] rank: 1 loading checkpoint: ../CPM-large_MP8/80000/mp_rank_01_model_states.pt
Loading extension module utils...
Time to load utils op: 0.10444498062133789 seconds
[2021-03-27 10:40:01,019] [INFO] [engine.py:1435:_load_checkpoint] rank: 2 loading checkpoint: ../CPM-large_MP8/80000/mp_rank_02_model_states.pt
Loading extension module utils...
Time to load utils op: 0.5052006244659424 seconds
[2021-03-27 10:40:01,090] [INFO] [engine.py:1435:_load_checkpoint] rank: 4 loading checkpoint: ../CPM-large_MP8/80000/mp_rank_04_model_states.pt
Using /home/ztx/.cache/torch_extensions as PyTorch extensions root...
Emitting ninja build file /home/ztx/.cache/torch_extensions/utils/build.ninja...
Building extension module utils...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
130 258
ninja: no work to do.
Loading extension module utils...
Time to load utils op: 0.6848421096801758 seconds
[2021-03-27 10:40:01,847] [INFO] [engine.py:1435:_load_checkpoint] rank: 0 loading checkpoint: ../CPM-large_MP8/80000/mp_rank_00_model_states.pt
130 258
130 258
Optimizer = FusedAdam
[2021-03-27 10:40:01,939] [INFO] [engine.py:591:_configure_optimizer] Removing param_group that has no 'params'in the client Optimizer
Optimizer = FusedAdam
[2021-03-27 10:40:02,038] [INFO] [engine.py:591:_configure_optimizer] Removing param_group that has no 'params'in the client Optimizer
Optimizer = FusedAdam
[2021-03-27 10:40:02,105] [INFO] [engine.py:591:_configure_optimizer] Removing param_group that has no 'params'in the client Optimizer
130 258
Optimizer = FusedAdam
[2021-03-27 10:40:02,313] [INFO] [engine.py:591:_configure_optimizer] Removing param_group that has no 'params'in the client Optimizer
Using /home/ztx/.cache/torch_extensions as PyTorch extensions root...
Using /home/ztx/.cache/torch_extensions as PyTorch extensions root...
Using /home/ztx/.cache/torch_extensions as PyTorch extensions root...
Using /home/ztx/.cache/torch_extensions as PyTorch extensions root...
Emitting ninja build file /home/ztx/.cache/torch_extensions/utils/build.ninja...
Building extension module utils...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module utils...
Loading extension module utils...
Time to load utils op: 0.5694868564605713 seconds
Time to load utils op: 0.20451569557189941 seconds
[2021-03-27 10:40:03,192] [INFO] [engine.py:1435:_load_checkpoint] rank: 5 loading checkpoint: ../CPM-large_MP8/80000/mp_rank_05_model_states.pt
[2021-03-27 10:40:03,192] [INFO] [engine.py:1435:_load_checkpoint] rank: 3 loading checkpoint: ../CPM-large_MP8/80000/mp_rank_03_model_states.pt
Loading extension module utils...
Time to load utils op: 0.5048840045928955 seconds
[2021-03-27 10:40:03,235] [INFO] [engine.py:1435:_load_checkpoint] rank: 7 loading checkpoint: ../CPM-large_MP8/80000/mp_rank_07_model_states.pt
Loading extension module utils...
Time to load utils op: 0.40515780448913574 seconds
[2021-03-27 10:40:03,249] [INFO] [engine.py:1435:_load_checkpoint] rank: 6 loading checkpoint: ../CPM-large_MP8/80000/mp_rank_06_model_states.pt
  successfully loaded ../CPM-large_MP8/80000/mp_rank_07_model_states.pt  successfully loaded ../CPM-large_MP8/80000/mp_rank_02_model_states.pt

  successfully loaded ../CPM-large_MP8/80000/mp_rank_05_model_states.pt
  successfully loaded ../CPM-large_MP8/80000/mp_rank_03_model_states.pt
  successfully loaded ../CPM-large_MP8/80000/mp_rank_00_model_states.pt
  successfully loaded ../CPM-large_MP8/80000/mp_rank_04_model_states.pt
  successfully loaded ../CPM-large_MP8/80000/mp_rank_01_model_states.pt
  successfully loaded ../CPM-large_MP8/80000/mp_rank_06_model_states.pt
  0%|                                                                                                                                                              | 0/1470 [00:00<?, ?it/s][2021-03-27 10:40:07,320] [INFO] [checkpointing.py:428:forward] Activation Checkpointing Information
[2021-03-27 10:40:07,321] [INFO] [checkpointing.py:429:forward] ----Partition Activations True, CPU CHECKPOINTING False
[2021-03-27 10:40:07,321] [INFO] [checkpointing.py:432:forward] ----contiguous Memory Checkpointing False with 32 total layers
[2021-03-27 10:40:07,321] [INFO] [checkpointing.py:435:forward] ----Synchronization False
[2021-03-27 10:40:07,321] [INFO] [checkpointing.py:436:forward] ----Profiling False
  0%|?                                                                                                                                                   | 3/1470 [00:33<4:27:28, 10.94s/it]Traceback (most recent call last):
  File "finetune_lm.py", line 315, in <module>
    main()
  File "finetune_lm.py", line 242, in main
    model.step()
  File "/home/ztx/anaconda3/envs/cpm/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1101, in step
    self._take_model_step(lr_kwargs)
  File "/home/ztx/anaconda3/envs/cpm/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1056, in _take_model_step
    self.optimizer.step()
  File "/home/ztx/anaconda3/envs/cpm/lib/python3.8/site-packages/apex/optimizers/fused_adam.py", line 159, in step
    multi_tensor_applier(self.multi_tensor_adam,
  File "/home/ztx/anaconda3/envs/cpm/lib/python3.8/site-packages/apex/multi_tensor_apply/multi_tensor_apply.py", line 27, in __call__
    return op(self.chunk_size,
RuntimeError: CUDA error: initialization error
Traceback (most recent call last):
  File "finetune_lm.py", line 315, in <module>
    main()
  File "finetune_lm.py", line 242, in main
    model.step()
  File "/home/ztx/anaconda3/envs/cpm/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1101, in step
    self._take_model_step(lr_kwargs)
  File "/home/ztx/anaconda3/envs/cpm/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1056, in _take_model_step
    self.optimizer.step()
  File "/home/ztx/anaconda3/envs/cpm/lib/python3.8/site-packages/apex/optimizers/fused_adam.py", line 159, in step
    multi_tensor_applier(self.multi_tensor_adam,
  File "/home/ztx/anaconda3/envs/cpm/lib/python3.8/site-packages/apex/multi_tensor_apply/multi_tensor_apply.py", line 27, in __call__
    return op(self.chunk_size,
RuntimeError: CUDA error: initialization error
Traceback (most recent call last):
  File "finetune_lm.py", line 315, in <module>
    main()
  File "finetune_lm.py", line 242, in main
    model.step()
  File "/home/ztx/anaconda3/envs/cpm/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1101, in step
    self._take_model_step(lr_kwargs)
  File "/home/ztx/anaconda3/envs/cpm/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1056, in _take_model_step
    self.optimizer.step()
  File "/home/ztx/anaconda3/envs/cpm/lib/python3.8/site-packages/apex/optimizers/fused_adam.py", line 159, in step
    multi_tensor_applier(self.multi_tensor_adam,
  File "/home/ztx/anaconda3/envs/cpm/lib/python3.8/site-packages/apex/multi_tensor_apply/multi_tensor_apply.py", line 27, in __call__
    return op(self.chunk_size,
RuntimeError: CUDA error: initialization error
Traceback (most recent call last):
  File "finetune_lm.py", line 315, in <module>
    main()
  File "finetune_lm.py", line 242, in main
    model.step()
  File "/home/ztx/anaconda3/envs/cpm/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1101, in step
    self._take_model_step(lr_kwargs)
  File "/home/ztx/anaconda3/envs/cpm/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1056, in _take_model_step
    self.optimizer.step()
  File "/home/ztx/anaconda3/envs/cpm/lib/python3.8/site-packages/apex/optimizers/fused_adam.py", line 159, in step
Traceback (most recent call last):
  File "finetune_lm.py", line 315, in <module>
    multi_tensor_applier(self.multi_tensor_adam,
  File "/home/ztx/anaconda3/envs/cpm/lib/python3.8/site-packages/apex/multi_tensor_apply/multi_tensor_apply.py", line 27, in __call__
    return op(self.chunk_size,
RuntimeError: CUDA error: initialization error
    main()
  File "finetune_lm.py", line 242, in main
    model.step()
  File "/home/ztx/anaconda3/envs/cpm/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1101, in step
Traceback (most recent call last):
  File "finetune_lm.py", line 315, in <module>
    self._take_model_step(lr_kwargs)
  File "/home/ztx/anaconda3/envs/cpm/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1056, in _take_model_step
    self.optimizer.step()
  File "/home/ztx/anaconda3/envs/cpm/lib/python3.8/site-packages/apex/optimizers/fused_adam.py", line 159, in step
    main()
  File "finetune_lm.py", line 242, in main
    multi_tensor_applier(self.multi_tensor_adam,
  File "/home/ztx/anaconda3/envs/cpm/lib/python3.8/site-packages/apex/multi_tensor_apply/multi_tensor_apply.py", line 27, in __call__
    return op(self.chunk_size,
    RuntimeErrormodel.step(): 
CUDA error: initialization error
  File "/home/ztx/anaconda3/envs/cpm/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1101, in step
    self._take_model_step(lr_kwargs)
  File "/home/ztx/anaconda3/envs/cpm/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1056, in _take_model_step
    self.optimizer.step()
  File "/home/ztx/anaconda3/envs/cpm/lib/python3.8/site-packages/apex/optimizers/fused_adam.py", line 159, in step
    multi_tensor_applier(self.multi_tensor_adam,
  File "/home/ztx/anaconda3/envs/cpm/lib/python3.8/site-packages/apex/multi_tensor_apply/multi_tensor_apply.py", line 27, in __call__
    return op(self.chunk_size,
RuntimeError: CUDA error: initialization error
  0%|?                                                                                                                                                   | 3/1470 [00:44<5:58:42, 14.67s/it]
Traceback (most recent call last):
  File "finetune_lm.py", line 315, in <module>
    main()
  File "finetune_lm.py", line 242, in main
    model.step()
  File "/home/ztx/anaconda3/envs/cpm/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1101, in step
    self._take_model_step(lr_kwargs)
  File "/home/ztx/anaconda3/envs/cpm/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1056, in _take_model_step
    self.optimizer.step()
  File "/home/ztx/anaconda3/envs/cpm/lib/python3.8/site-packages/apex/optimizers/fused_adam.py", line 159, in step
    multi_tensor_applier(self.multi_tensor_adam,
  File "/home/ztx/anaconda3/envs/cpm/lib/python3.8/site-packages/apex/multi_tensor_apply/multi_tensor_apply.py", line 27, in __call__
    return op(self.chunk_size,
RuntimeError: CUDA error: initialization error
Traceback (most recent call last):
  File "finetune_lm.py", line 315, in <module>
    main()
  File "finetune_lm.py", line 242, in main
    model.step()
  File "/home/ztx/anaconda3/envs/cpm/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1101, in step
    self._take_model_step(lr_kwargs)
  File "/home/ztx/anaconda3/envs/cpm/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1056, in _take_model_step
    self.optimizer.step()
  File "/home/ztx/anaconda3/envs/cpm/lib/python3.8/site-packages/apex/optimizers/fused_adam.py", line 159, in step
    multi_tensor_applier(self.multi_tensor_adam,
  File "/home/ztx/anaconda3/envs/cpm/lib/python3.8/site-packages/apex/multi_tensor_apply/multi_tensor_apply.py", line 27, in __call__
    return op(self.chunk_size,
RuntimeError: CUDA error: initialization error
Traceback (most recent call last):
  File "/home/ztx/anaconda3/envs/cpm/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ztx/anaconda3/envs/cpm/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ztx/anaconda3/envs/cpm/lib/python3.8/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/home/ztx/anaconda3/envs/cpm/lib/python3.8/site-packages/torch/distributed/launch.py", line 256, in main
    raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command '['/home/ztx/anaconda3/envs/cpm/bin/python3', '-u', 'finetune_lm.py', '--local_rank=7', '--do_train', '--do_eval', '--data_dir', '../STC', '--model-parallel-size', '8', '--num-layers', '32', '--hidden-size', '2560', '--load', '../CPM-large_MP8', '--num-attention-heads', '32', '--seq-length', '200', '--max-position-embeddings', '1024', '--tokenizer-type', 'GPT2BPETokenizer', '--tokenizer-path', 'bpe_3w_new/', '--vocab-size', '30000', '--lr', '0.00001', '--warmup', '0.1', '--batch-size', '16', '--deepspeed', '--deepspeed_config', '/DATACENTER/ztx/cpm_model/fine/scripts/language_model/../ds_config/ds_finetune_lm_large_fp32.json', '--log-interval', '10', '--eval-interval', '100', '--seed', '23333', '--results_dir', 'results/', '--model_name', 'finetune-dial-large-fp32', '--epoch', '1', '--checkpoint-activations', '--deepspeed-activation-checkpointing']' returned non-zero exit status 1.

**Comment by t1101675** [comment]
您好！请问您解决这个问题了吗？我们尝试了很多次都无法复现这个问题。猜测是 apex 安装时候出现的 bug，所以如果还没有解决的话，我们推荐您使用我们提供的 docker 容器，具体安装方式见 README.md

**Comment by holalula** [comment]
解决了。应该是apex安装过程的问题，我把整个环境重新装一遍就好了。
